# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
connection: &connection
  adapter: postgresql
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432

development:
  adapter: postgresql
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432
  database: database

test:
  adapter: postgresql
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432
  database: my_database_test

production:
  adapter: postgresql
  pool: 5
  username: postgres
  password: admin
  host: localhost
  port: 5432
  database: database